"""Format the measured stage study using the official JCS&T v1.12 template."""
from pathlib import Path
import json
import re
import shutil
import subprocess
import zipfile
import hashlib
import os
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

ROOT=Path(__file__).resolve().parent
DEST=ROOT/'paper_jcst'
OUTPUT=ROOT.parent/'output'
TEX=Path(os.environ.get('TEX_BIN',str(Path(shutil.which('pdflatex') or 'C:/texlive/2026/bin/windows/pdflatex.exe').parent)))

SPANISH=r'''Estimamos valores relativos de las piezas de ajedrez a partir de elecciones de Stockfish 18 mediante aprendizaje por refuerzo inverso de máxima entropía de un paso. El valor es un coeficiente de recompensa condicionado al modelo, no un precio estratégico intrínseco. Utilizamos 300 partidas de autojuego y 18\,351 posiciones para resumir apertura, medio juego y final. En el modelo contextual conjunto, los coeficientes del caballo normalizados respecto al peón son 2,64, 1,50 y 0,87. Ajustamos además modelos independientes para posiciones con pocas, intermedias y muchas piezas: los coeficientes del caballo son 0,40, 1,43 y 1,89. Comparamos las configuraciones de fuerza 1500, 2000 y 2500 en las mismas posiciones; estas etiquetas no equivalen a puntuaciones Elo humanas verificadas. Presentamos intervalos de remuestreo por partida, sensibilidad a regularización y límites de grupos, y diagnósticos de soporte. Los resultados dependen de la especificación y de la población de estados. Todas las extensiones son exploratorias y pertenecen a la misma familia de modelos. El código, los datos y los resultados están disponibles públicamente.'''

BIB=r'''@inproceedings{david,
 author={David, Omid E. and van den Herik, H. Jaap and Koppel, Moshe and Netanyahu, Nathan S.},
 title={Simulating Human Grandmasters: Evolution and Coevolution of Evaluation Functions},
 booktitle={Proc. Genetic and Evolutionary Computation Conference (GECCO)},
 year={2009}, pages={1483--1489}, url={https://arxiv.org/abs/1711.06840}}
@inproceedings{palsson,
 author={P{\'a}lsson, A{\dh}alsteinn and Bj{\"o}rnsson, Yngvi},
 title={Unveiling Concepts Learned by a World-Class Chess-Playing Agent},
 booktitle={Proc. 32nd International Joint Conference on Artificial Intelligence (IJCAI)},
 year={2023}, pages={4864--4872}, doi={10.24963/ijcai.2023/541},
 url={https://www.ijcai.org/proceedings/2023/541}}
@misc{pawn, author={Tang, Ethan and Davulcu, Hasan and Zou, Jia and Zhang, Zhongju},
 title={{PAWN}: Piece Value Analysis with Neural Networks}, year={2026},
 howpublished={arXiv:2604.15585}, url={https://arxiv.org/abs/2604.15585}}
@inproceedings{ziebart,
 author={Ziebart, Brian D. and Maas, Andrew L. and Bagnell, J. Andrew and Dey, Anind K.},
 title={Maximum Entropy Inverse Reinforcement Learning},
 booktitle={Proc. 23rd AAAI Conference on Artificial Intelligence}, year={2008}, pages={1433--1438},
 url={https://www.cs.cmu.edu/~bziebart/publications/maximum-entropy-inverse-reinforcement-learning.html}}
@inproceedings{kim,
 author={Kim, Kuno and Garg, Shivam and Shiragur, Kirankumar and Ermon, Stefano},
 title={Reward Identification in Inverse Reinforcement Learning},
 booktitle={Proc. 38th International Conference on Machine Learning},
 series={Proceedings of Machine Learning Research}, volume={139}, year={2021}, pages={5496--5505},
 url={https://proceedings.mlr.press/v139/kim21c.html}}
@misc{stockfish, author={{Stockfish developers}}, title={{Stockfish 18}}, year={2026},
 url={https://github.com/official-stockfish/Stockfish/releases/tag/sf_18}}
'''

DECLARATIONS=r'''
\begin{small}
\authorcontributions{J.K.: Conceptualization, Methodology, Software, Validation, Formal analysis, Investigation, Data curation, Visualization, Writing---original draft, and Writing---review and editing.}
\competinginterests{The author declares that no competing interests exist.}
\aideclaration{During preparation of this work, OpenAI Codex (OpenAI; a GPT-6-based assistant) assisted with research design, software implementation, numerical analysis, manuscript drafting, translation, and formatting. Its use extended beyond language editing. Numerical results were generated by the accompanying programs. J.K. is responsible for verifying and editing the content and for the integrity of the reported research. The exact application build and extension identifiers were not recorded.}
\dataavailability{The code, 300 self-play game histories, retained-position splits, fitted coefficients, bootstrap draws, and extension results are available at \url{https://github.com/rlawjdqls1212/piece-values-irl}. The repository documents software versions, engine settings, reproduction commands, and data checksums. The original engine executable is obtained separately from the official Stockfish release.}
\funding{This research received no external funding.}
\end{small}
'''

BOX=r'''
\medskip
\noindent\cornersize{.2}\setlength{\fboxsep}{6pt}
\ovalbox{\begin{minipage}{\dimexpr\columnwidth-2\fboxsep-2\fboxrule\relax}
\small
\textbf{Citation:} J. Kim. \emph{Stage-Specific Relative Chess Piece Values Estimated with One-Step Maximum-Entropy IRL}. Journal of Computer Science \& Technology. Publication metadata to be assigned by the journal.\\[3pt]
\textbf{DOI:} To be assigned.\\
\textbf{Received / Accepted:} To be assigned.\\
\textbf{Copyright:} Journal publication license: CC-BY-NC-SA. This manuscript has not been accepted or published.
\end{minipage}}
\end{document}
'''

def main():
    DEST.mkdir(exist_ok=True)
    (OUTPUT/'pdf').mkdir(parents=True,exist_ok=True)
    for f in ['jcst.cls','IEEEtran.bst']:
        shutil.copy2(ROOT/'jcst_template'/f,DEST/f)
    # Match the class's lowercase style name also on case-sensitive systems.
    shutil.copy2(ROOT/'jcst_template'/'IEEEtran.bst',DEST/'ieeetran.bst') if not (DEST/'ieeetran.bst').exists() else None
    source=(ROOT/'paper'/'main.tex').read_text(encoding='utf-8')
    expanded=(DEST/'introduction.tex').read_text(encoding='utf-8')+'\n'+(DEST/'related_work.tex').read_text(encoding='utf-8')+'\n'
    a=source.index(r'\section{Introduction}');b=source.index(r'\section{One-step maximum-entropy IRL}')
    source=source[:a]+expanded+source[b:]
    abstract='We estimate relative chess piece values from Stockfish 18 choices using one-step maximum-entropy inverse reinforcement learning. Value denotes a model-conditional reward coefficient, not an intrinsic strategic exchange price. Using 300 self-play games and 18,351 retained positions, we summarize opening, middlegame, and endgame coefficients. In the pooled contextual model, pawn-normalized knight estimates are 2.64, 1.50, and 0.87. Independently fitted sparse, intermediate, and dense piece-count groups yield knight estimates of 0.40, 1.43, and 1.89. We additionally compare engine strength settings 1500, 2000, and 2500 on the same positions; these labels are not verified human Elo ratings. We report game-bootstrap intervals, regularization and boundary sensitivity, and feature-support diagnostics. Results depend on the specification and state population. All extensions are exploratory and remain within the same horizon-one model family. Code, data, and measured results are publicly available.'
    abstract=abstract.replace('horizon-one IRL family','horizon-one inverse reinforcement learning family')
    assert len(abstract.split())<200 and len(SPANISH.split())<200
    head=r'''\documentclass{jcst}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[spanish,english]{babel}
\usepackage{placeins}
\usepackage{xurl}
\hypersetup{pageanchor=false,pdftitle={Stage-Specific Relative Chess Piece Values Estimated with One-Step Maximum-Entropy IRL},pdfauthor={Jungbin Kim}}
\setlength{\tabcolsep}{3pt}
\setlength{\emergencystretch}{1em}
\title{Stage-Specific Relative Chess Piece Values Estimated with One-Step Maximum-Entropy IRL\\
\large Estimación de valores relativos de las piezas de ajedrez según la fase de la partida mediante aprendizaje por refuerzo inverso de máxima entropía de un paso}
\author[1\orcid{0009-0000-4719-1228}]{Jungbin Kim}
\affil[1]{UNIST Department of Engineering\authorcr
Corresponding author: \href{mailto:rlawjdqls1212@unist.ac.kr}{rlawjdqls1212@unist.ac.kr}\authorcr
ORCID: \href{https://orcid.org/0009-0000-4719-1228}{0009-0000-4719-1228}}
\begin{document}
\maketitle
\begin{abstract}
'''+abstract+r'''
\end{abstract}
\par
\keywords{Chess, contextual rewards, inverse reinforcement learning, maximum entropy, piece values.}
\selectlanguage{spanish}
\begin{abstract}
'''+SPANISH+r'''
\end{abstract}
\par
\palabrasclaves{Ajedrez, aprendizaje por refuerzo inverso, máxima entropía, recompensas contextuales, valores de las piezas.}
\selectlanguage{english}

'''
    body=source[source.index(r'\section{Introduction}'):source.index(r'\begin{thebibliography}')]
    body=re.sub(r'\\section\*\{Data, code, and tool use\}.*?(?=\\appendix)', '', body, flags=re.S)
    body=body.replace(r'\FloatBarrier','')
    body=body.replace(r'\[',r'\begin{equation}').replace(r'\]',r'\end{equation}')
    body=body.replace('Figure~', 'Fig.~')
    body=body.replace('The validation-selected penalties lie on the lower boundary', 'For the original pooled models, the selected penalties lie on the lower boundary')
    body=body.replace(r'\section{Piece-wise interpretation}',(DEST/'count_results.tex').read_text(encoding='utf-8')+'\n'+r'\section{Piece-wise interpretation}')
    if (DEST/'elo_results.tex').exists():
        body=body.replace(r'\section{Piece-wise interpretation}',(DEST/'elo_results.tex').read_text(encoding='utf-8')+'\n'+r'\section{Piece-wise interpretation}')
    # Consolidate repeated piece-by-piece discussion into the measured result sections.
    body=re.sub(r'\\section\{Piece-wise interpretation\}.*?(?=\\section\{Limitations and conclusion\})','',body,flags=re.S)
    body=body.replace(' No fabricated value table or unexecuted algorithm is presented as an experiment.','')
    body=body.replace('For the pooled contextual model, we first average',r'Table~\ref{tab:coverage} summarizes the stage reference populations. For the pooled contextual model, we first average')
    body=body.replace('the displayed paired opening-to-endgame difference intervals',r'the paired intervals in Table~\ref{tab:contrast}')
    body=body.replace('The independently fitted opening estimates differ substantially',r'The independent opening estimates in Table~\ref{tab:independent} differ substantially')
    body=body.replace('The effect is small. A lower prediction loss',r'The effect is small. Table~\ref{tab:stageperf} reports stage-level checks. A lower prediction loss')
    body=body.replace(r'width=0.95\textwidth',r'width=\columnwidth').replace(r'width=\textwidth',r'width=\columnwidth')
    def table(match):
        t=match.group()
        if any(r'\label{tab:'+label+'}' in t for label in ['primary','independent','stageperf']):
            return t.replace(r'\begin{table}[htbp]',r'\begin{table*}[t]').replace(r'\end{table}',r'\end{table*}')
        return t.replace('[htbp]','[tbp]')
    body=re.sub(r'\\begin\{table\}\[htbp\].*?\\end\{table\}',table,body,flags=re.S)
    # Keep research content and all measured tables; declarations are completed separately by authors.
    body += (DEST/'mathematical_note.tex').read_text(encoding='utf-8')
    text=head+body+r'\FloatBarrier'+DECLARATIONS+r'\bibliography{references}'+BOX
    text=text.replace(r'\dimexpr\columnwidth-2\fboxsep-2\fboxrule\relax',r'\dimexpr\columnwidth-2\fboxsep-2\fboxrule-2pt\relax')
    (DEST/'main.tex').write_text(text,encoding='utf-8')
    (DEST/'references.bib').write_text(BIB+(DEST/'additional_references.bib').read_text(encoding='utf-8'),encoding='utf-8')
    estimates=json.loads((ROOT/'runs/stage_analysis/summary.json').read_text())['estimates']
    plt.rcParams.update({'font.size':8})
    fig,ax=plt.subplots(figsize=(3.0,2.4),layout='constrained')
    for k,r in enumerate(estimates):
        v=np.array(r['ratios'])[1:]; ci=np.array(r['ratio_ci95'])[:,1:]
        ax.errorbar(np.arange(4)+(k-1)*.16,v,yerr=[v-ci[0],ci[1]-v],fmt=['o','s','^'][k],
                    markersize=3,capsize=2,label=r['stage'].title())
    ax.set_xticks(range(4),['Knight','Bishop','Rook','Queen'])
    ax.set_ylabel('Coefficient / pawn coefficient')
    ax.set_ylim(0,7.2);ax.legend(frameon=False,fontsize=7)
    ax.spines[['top','right']].set_visible(False)
    fig.savefig(DEST/'stage_values.png',dpi=300)
    plt.close(fig)
    for exe,args in [('pdflatex',['-interaction=nonstopmode','-halt-on-error','main.tex']),
                     ('bibtex',['main']),('pdflatex',['-interaction=nonstopmode','-halt-on-error','main.tex']),
                     ('pdflatex',['-interaction=nonstopmode','-halt-on-error','main.tex'])]:
        p=subprocess.run([str(TEX/(exe+('.exe' if os.name=='nt' else ''))),*args],cwd=DEST,capture_output=True,text=True,errors='replace')
        if p.returncode:raise RuntimeError(p.stdout[-4500:])
    shutil.copy2(DEST/'main.pdf',OUTPUT/'pdf/jcst_manuscript.pdf')
    with zipfile.ZipFile(OUTPUT/'jcst_manuscript_source.zip','w',zipfile.ZIP_DEFLATED) as z:
        for f in ['main.tex','main.bbl','references.bib','jcst.cls','stage_values.png']:
            z.write(DEST/f,f)
        z.write(DEST/'IEEEtran.bst','ieeetran.bst')
    print('Built JCS&T manuscript and source ZIP.')

if __name__=='__main__':main()
